# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e49d2744ee3413c38202268274a83498f297a27d809bb44227fa23a504e9775b89e9dbf19c17ed8895f3462b13df96183414d54e9a47c6b5bd2c3194e6c676

test:
  secret_key_base: 6b64eee6d0bba9be7eaf6869c3ad1818ca9c0d9caaad67b490b30930c0fd5b46c02fcbbf9c516ccd4997f85e5ee7bcb5ca4f12285d336b7141e414f3130ccebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
